"use client"
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones, configureBoneyard } from 'boneyard-js/react'

import _user_sheet_list from './user-sheet-list.bones.json'

configureBoneyard({"color":"#e5e5e5","animate":"pulse"})

registerBones({
  "user-sheet-list": _user_sheet_list,
})
